### ISSUE TITLE
影响了子目录的展示，不知道为何？

### ISSUE THREAD

**Issue by Ghostwritten** [T-miracle/gitbook-plugin-zymplayer#1]
效果：https://smoothies.com.cn/gitbook-demo/Gitbook/
https://smoothies.com.cn/python-docs/Case/
加上这个模块都开始出现这个问题。

**Comment by T-miracle** [comment]
请检查position参数是否设置正确



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [T-miracle/gitbook-plugin-zymplayer] 影响了子目录的展示，不知道为何？ (Issue #1)




 
效果：https://smoothies.com.cn/gitbook-demo/Gitbook/

**Comment by T-miracle** [comment]
参考
http://www.zhangyumiao.com/docs/project/zym-player.html




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [T-miracle/gitbook-plugin-zymplayer] 影响了子目录的展示，不知道为何？ (Issue #1)




 
效果：https://smoothies.com.cn/gitbook-demo/Gitbook/

**Comment by T-miracle** [comment]
如果你想放在右下角，建议设置参数
```json
"position": {
                "pos": "fixed",
                "right": "0px", 
                "bottom": "0px"
                }
```
如果你想固定在页面某处
pos参数可以改成absolute
